"""Auditable philosophical analysis primitives. No LLM or network required.

The engine analyses supplied argument structures, not people's intentions or truth.
"""
from __future__ import annotations
import ast
import itertools
import re
from typing import Any
from sympy import Symbol, And, Or, Not, Implies, Equivalent, true, false
from sympy.logic.inference import satisfiable

METHODS = {
    "socratic": ("Definition and consistency", ["What exactly does the central term mean?", "What would count as an exception?", "Does the same principle hold in a parallel case?"], "Questions probe a position; they do not by themselves disprove it."),
    "humean": ("Evidence and causation", ["What has actually been observed?", "What bridges observation and the causal conclusion?", "Which alternative explanation is compatible with the evidence?"], "Causal inference often needs empirical research."),
    "aristotelian": ("Inference and categories", ["Which premises yield the conclusion?", "Are terms used in the same sense throughout?", "Is the inference deductive, inductive or analogical?"], "Validity does not establish the truth of premises."),
    "kantian": ("Duties and universal principles", ["What maxim does the action express?", "Could everyone act on this maxim coherently?", "Are persons being treated merely as means?"], "A Kantian lens is not a universal ethical verdict."),
    "consequentialist": ("Consequences and trade-offs", ["What outcomes are plausible?", "Who bears risks and receives benefits?", "How do we compare uncertain long-term effects?"], "Predicted consequences and value weights require evidence and judgment."),
    "rawlsian": ("Fairness and institutions", ["Would this arrangement seem fair without knowing one's own position?", "Who is least advantaged?", "Which basic liberties are at stake?"], "This applies one tradition of political philosophy, not an uncontested test."),
    "wittgensteinian": ("Meaning and language use", ["How is the disputed word used in different settings?", "Does a definitional dispute conceal several different questions?", "What changes if we use a more precise description?"], "Language analysis alone does not settle every empirical or ethical disagreement."),
    "genealogical": ("Historical origins of values", ["How did this category or value develop historically?", "Whose interests and institutions shaped its use?", "Has its meaning changed over time?"], "Historical origin alone does not invalidate a belief."),
    "pragmatist": ("Consequences of inquiry", ["What practical difference would either view make?", "What experience could revise the belief?", "Can the disagreement be turned into a testable question?"], "Practical success is not identical to truth in every philosophical tradition."),
    "care_ethics": ("Relationships and dependence", ["Who is affected in their relationships and vulnerabilities?", "What responsibilities follow from dependency?", "Whose experience may be missing?"], "This lens need not replace rights or distributive-justice analyses."),
    "machine_epistemics": ("Human-AI division of epistemic labour", ["Which propositions were generated by a model and which were independently checked?", "What evidence would falsify the system’s preferred answer?", "Which interpretative or ethical judgments remain human responsibilities?"], "This is a proposed contemporary lens, not an established historical school."),
    "nyaya": ("Means of knowledge and inference", ["What is the claimed source of knowledge?", "How is the inference supported?", "Is the example genuinely probative?"], "Nyāya is a rich tradition and cannot be reduced to these prompts."),
}

KEYWORDS = {
    "socratic": ["definition", "define", "what is", "always", "never", "all", "anyone", "contradiction"],
    "humean": ["because", "cause", "proof", "evidence", "study", "fact", "science", "research"],
    "aristotelian": ["therefore", "logic", "valid", "implies", "must", "if ", "conclude"],
    "kantian": ["duty", "right", "ought", "obligation", "moral", "wrong"],
    "consequentialist": ["harm", "benefit", "outcome", "impact", "effect", "better"],
    "rawlsian": ["fair", "justice", "equal", "inequality", "policy", "society"],
    "wittgensteinian": ["word", "mean", "language", "identity", "name", "woman", "freedom"],
    "genealogical": ["history", "origin", "tradition", "power", "value", "norm"],
    "pragmatist": ["work", "useful", "practical", "change", "test"],
    "care_ethics": ["care", "family", "health", "relationship", "dependency"],
    "nyaya": ["knowledge", "inference", "testimony", "perception"],
    "machine_epistemics": ["chatgpt", "machine", "algorithm", "ai", "model", "automation", "technology"],
}


def choose_methods(question: str, count: int = 3) -> dict[str, Any]:
    if not question.strip():
        raise ValueError("question cannot be empty")
    if not 1 <= count <= 6:
        raise ValueError("count must be between 1 and 6")
    q = question.casefold()
    matches = {name: [w for w in words if re.search(r"(?<!\w)" + re.escape(w.strip()) + r"(?!\w)", q)] for name, words in KEYWORDS.items()}
    scores = {name: len(hits) for name, hits in matches.items()}
    baseline = ["socratic", "humean", "wittgensteinian", "rawlsian", "aristotelian", "care_ethics"]
    selected = sorted(METHODS, key=lambda n: (-scores[n], baseline.index(n) if n in baseline else len(baseline)))[:count]
    return {"question": question, "selection_method": "transparent keyword heuristic, not philosophical judgment", "methods": [
        {"id": n, "purpose": METHODS[n][0], "questions": METHODS[n][1], "limitation": METHODS[n][2], "keyword_matches": matches[n]} for n in selected
    ]}


def socratic_questions(claim: str, assumptions: list[str] | None = None) -> dict[str, Any]:
    if not claim.strip():
        raise ValueError("claim cannot be empty")
    assumptions = assumptions or []
    questions = [
        "Which key term in the claim needs an agreed definition?",
        "Is the claim universal, conditional, statistical or about one specific case?",
        "What would the claimant accept as a genuine counterexample?",
        "Which premise, if mistaken, would most weaken the conclusion?",
        "Does applying the same reasoning to a relevant comparison produce a result the claimant would also endorse?",
        "Is the apparent disagreement factual, conceptual, ethical or partly verbal?",
        "What is the strongest charitable interpretation of the opposing view?",
        "What new evidence or argument could make either side revise its position?",
    ]
    for a in assumptions[:4]:
        questions.append(f"What reason supports the assumption '{a}' rather than a competing assumption?")
    return {"claim": claim, "questions": questions, "method": "Socratic examination; questions are prompts, not discovered contradictions"}


def reconstruct_argument(text: str) -> dict[str, Any]:
    """Extract only explicitly marked inferential fragments; avoid fabricated premises."""
    if not text.strip():
        raise ValueError("text cannot be empty")
    cleaned = " ".join(text.split())
    m = re.search(r"\b(?:therefore|thus|hence|consequently)\b[, :]*", cleaned, re.I)
    if m:
        premise, conclusion = cleaned[:m.start()].strip(" ,.;"), cleaned[m.end():].strip()
        candidates = [premise] if premise else []
    else:
        m = re.search(r"\bbecause\b", cleaned, re.I)
        if m:
            conclusion, premise = cleaned[:m.start()].strip(" ,.;"), cleaned[m.end():].strip(" ,.;")
            candidates = [premise] if premise else []
        else:
            conclusion, candidates = "", []
    return {
        "original": text,
        "explicit_premise_fragments": candidates,
        "explicit_conclusion_fragment": conclusion,
        "status": "candidate_extraction" if conclusion and candidates else "insufficient_explicit_structure",
        "unresolved": ["Check quotation boundaries and whether these fragments express the speaker's intended argument.",
                       "Implicit premises and inference rules have not been invented."],
        "requires_human_review": True,
    }


def _clean_line(s: str) -> str:
    return " ".join(s.replace("<", "‹").replace(">", "›").replace("[", "〔").replace("]", "〕").split())[:1000]


def argument_to_argdown(premises: list[str], conclusion: str, objections: list[str] | None = None) -> dict[str, Any]:
    if not premises or not conclusion.strip() or any(not p.strip() for p in premises):
        raise ValueError("at least one premise and a conclusion are required")
    if len(premises) > 20 or len(objections or []) > 20:
        raise ValueError("at most 20 premises and 20 objections")
    lines = ["# Argument reconstruction", "", "<Main argument>", ""]
    for i, premise in enumerate(premises, 1):
        lines.append(f"({i}) {_clean_line(premise)}")
    lines += ["----", f"({len(premises) + 1}) {_clean_line(conclusion)}"]
    if objections:
        lines += ["", "# Objections", ""]
        for i, objection in enumerate(objections, 1):
            lines += [f"<Objection {i}>: {_clean_line(objection)}", "    -> <Main argument>", ""]
    return {"argdown": "\n".join(lines), "format": "Argdown", "note": "The reconstruction records supplied premises; it does not verify that the inference is valid or the premises true.", "preview_url": "https://argdown.org/sandbox/"}


class _FormulaParser(ast.NodeVisitor):
    def __init__(self) -> None:
        self.names: dict[str, Symbol] = {}

    def visit_Name(self, node: ast.Name):
        if node.id in ("True", "False"):
            return true if node.id == "True" else false
        if len(self.names) > 12:
            raise ValueError("at most 12 distinct propositional variables")
        return self.names.setdefault(node.id, Symbol(node.id))

    def visit_UnaryOp(self, node: ast.UnaryOp):
        if isinstance(node.op, (ast.Not, ast.Invert)):
            return Not(self.visit(node.operand))
        raise ValueError("only NOT or ~ are supported as unary operators")

    def visit_BoolOp(self, node: ast.BoolOp):
        values = [self.visit(x) for x in node.values]
        if isinstance(node.op, ast.And): return And(*values)
        if isinstance(node.op, ast.Or): return Or(*values)
        raise ValueError("only and/or are supported")

    def visit_BinOp(self, node: ast.BinOp):
        a, b = self.visit(node.left), self.visit(node.right)
        if isinstance(node.op, ast.RShift): return Implies(a, b)
        if isinstance(node.op, ast.BitAnd): return And(a, b)
        if isinstance(node.op, ast.BitOr): return Or(a, b)
        if isinstance(node.op, ast.BitXor): return ~Equivalent(a, b)
        raise ValueError("only >>, &, | and ^ are supported")

    def visit_Compare(self, node: ast.Compare):
        if len(node.ops) != 1 or len(node.comparators) != 1:
            raise ValueError("only one comparison is supported")
        a, b = self.visit(node.left), self.visit(node.comparators[0])
        if isinstance(node.ops[0], ast.Eq): return Equivalent(a, b)
        if isinstance(node.ops[0], ast.NotEq): return Not(Equivalent(a, b))
        raise ValueError("only == and != are supported")

    def generic_visit(self, node):
        raise ValueError(f"unsupported syntax: {type(node).__name__}")


def _parse_formula(s: str, parser: _FormulaParser):
    try:
        return parser.visit(ast.parse(s, mode="eval").body)
    except SyntaxError as exc:
        raise ValueError("Use P >> Q for implication; P and Q; P or Q; not P; or P == Q") from exc


def verify_formal(premises: list[str], conclusion: str) -> dict[str, Any]:
    """Propositional validity: premises entail conclusion iff no countermodel exists."""
    if not premises or not conclusion or len(premises) > 25:
        raise ValueError("supply 1-25 premises and a conclusion")
    parser = _FormulaParser()
    propositions = [_parse_formula(s, parser) for s in premises]
    claim = _parse_formula(conclusion, parser)
    if len(parser.names) > 12:
        raise ValueError("at most 12 propositional variables")
    premise_model = satisfiable(And(*propositions), all_models=False)
    if premise_model is False:
        return {"status": "inconsistent_premises", "valid": None, "countermodel": None, "warning": "Premises contradict each other; classical entailment would be vacuous. Review the formalisation.", "scope": "propositional logic only"}
    counter = satisfiable(And(*(propositions + [Not(claim)])), all_models=False)
    if counter is False:
        return {"status": "valid", "valid": True, "countermodel": None, "scope": "propositional logic only", "warning": "Validity assumes this precise formalisation and does not establish premise truth."}
    model = {name: bool(counter.get(sym, False)) for name, sym in parser.names.items() if sym in counter}
    return {"status": "invalid", "valid": False, "countermodel": model, "scope": "propositional logic only", "warning": "A countermodel invalidates this formalisation, not necessarily the intended natural-language argument."}


def argumentation_graph(arguments: list[str], attacks: list[list[str]]) -> dict[str, Any]:
    """Compute Dung-style grounded, preferred and stable extensions (max 12 nodes)."""
    if len(arguments) != len(set(arguments)) or not 1 <= len(arguments) <= 12 or any(not s for s in arguments):
        raise ValueError("provide 1-12 unique nonempty argument IDs")
    ids = set(arguments)
    edges = set()
    for e in attacks:
        if len(e) != 2 or e[0] not in ids or e[1] not in ids:
            raise ValueError("each attack must be [attacker_id, target_id] using declared IDs")
        edges.add(tuple(e))
    attackers = {n: {a for a, b in edges if b == n} for n in ids}
    accepted: set[str] = set()
    while True:
        attacked = {b for a, b in edges if a in accepted}
        updated = accepted | {n for n in ids if attackers[n] <= attacked}
        if updated == accepted: break
        accepted = updated
    rejected = {b for a, b in edges if a in accepted}
    def conflict_free(ss): return not any(a in ss and b in ss for a, b in edges)
    def admissible(ss):
        defeated = {b for a, b in edges if a in ss}
        return conflict_free(ss) and all(attackers[a] <= defeated for a in ss)
    subsets = [set(c) for k in range(len(ids)+1) for c in itertools.combinations(sorted(ids), k)]
    admissible_sets = [s for s in subsets if admissible(s)]
    preferred = [sorted(s) for s in admissible_sets if not any(s < t for t in admissible_sets)]
    stable = [sorted(s) for s in subsets if conflict_free(s) and ids - s <= {b for a, b in edges if a in s}]
    return {"grounded": {"in": sorted(accepted), "out": sorted(rejected), "undecided": sorted(ids-accepted-rejected)},
            "preferred_extensions": preferred, "stable_extensions": stable,
            "scope": "abstract attacks only; semantic acceptance is not real-world truth", "attacks": sorted(list(edges))}


def conclusion_audit(claim: str, premises: list[str], evidence: list[str] | None = None, objections: list[str] | None = None, sources: list[str] | None = None) -> dict[str, Any]:
    if not claim.strip(): raise ValueError("claim cannot be empty")
    evidence, objections, sources = evidence or [], objections or [], sources or []
    gaps = []
    if not premises: gaps.append("No explicit premises supplied.")
    if not evidence: gaps.append("No evidence supplied for factual premises.")
    if not objections: gaps.append("No objections recorded or tested.")
    if not sources: gaps.append("No independently checkable sources supplied.")
    return {"claim": claim, "premises": premises, "evidence_as_supplied_unverified": evidence,
            "objections_as_supplied": objections, "source_identifiers_unverified": sources,
            "gaps": gaps, "status": "unverified_analysis_record", "truth_verdict": "not_assessed",
            "next_checks": ["Check the faithful reconstruction against the original source.",
                            "Check inferential validity separately from evidence quality.",
                            "Investigate strongest alternative and what would change the conclusion."]}


def lookup_scholarly_sources(query: str, limit: int = 5) -> dict[str, Any]:
    """Live Crossref bibliographic metadata; never present results as verified evidence."""
    if not query.strip() or len(query) > 250 or not 1 <= limit <= 10:
        raise ValueError("query must be 1-250 characters; limit 1-10")
    import httpx
    try:
        r = httpx.get("https://api.crossref.org/works", params={"query.bibliographic": query, "rows": limit},
                      headers={"User-Agent": "PhilosophyMCP/0.1 (research metadata lookup)"}, timeout=12.0, follow_redirects=False)
        r.raise_for_status()
        entries = r.json()["message"]["items"]
    except (httpx.RequestError, httpx.HTTPStatusError, ValueError, KeyError) as exc:
        return {"status": "lookup_failed", "reason": str(exc), "results": []}
    results = [{"title": (w.get("title") or [""])[0], "year": (w.get("published", {}).get("date-parts") or [[None]])[0][0],
                "doi": w.get("DOI"), "url": w.get("URL"),
                "authors": [a.get("family", "") for a in w.get("author", [])[:5]]} for w in entries]
    return {"status": "metadata_only", "query": query, "results": results,
            "warning": "Matches are not verified as relevant, readable, correct or supportive. Check primary sources and their full text."}